services:
  gateway:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: llm-gateway-container
    command: uvicorn app.main:app --host 0.0.0.0 --port 8000 --reload
    ports:
      - "8000:8000"
    env_file:
      - .env
    environment:
      - WATCHFILES_FORCE_POLLING=true
    volumes:
      - ./app:/code/app
    depends_on:
      - redis    
      - mongodb     
    restart: always

  redis:
    image: redis:7-alpine
    container_name: llm-gateway-redis
    ports:
      - "6379:6379"   
    restart: always

  mongodb:           
    image: mongo:latest
    container_name: llm-gateway-mongodb
    ports:
      - "27018:27017"
    volumes:
      - mongo_data:/data/db  
    restart: always
    


  qdrant:
    image: qdrant/qdrant:latest
    container_name: llm-gateway-qdrant
    ports:
      - "6333:6333"   
      - "6334:6334" 
    volumes:
      - qdrant_data:/qdrant/storage
    restart: always


volumes:
  mongo_data:
  qdrant_data: