
services:
  gateway:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: llm-gateway-container
    ports:
      - "8000:8000"
    env_file:
      - .env
    volumes:
      - ./app:/code/app
    depends_on:
      - redis    
      - mongodb     
    restart: always

  redis:
    image: redis:7-alpine
    container_name: llm-gateway-redis
    ports:
      - "6379:6379"   
    restart: always


  mongodb:           
    image: mongo:latest
    container_name: llm-gateway-mongodb
    ports:
      - "27018:27017"
    volumes:
      - mongo_data:/data/db  
    restart: always
    

volumes:
  mongo_data: